server:
  port: 8003
spring:
  application:
    name: microservice-provider-order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true