drop table user if exists;
create table user (id bigint generated by default as identity, username varchar(40), name varchar(20), age int(3), balance decimal(10,2), primary key (id));


-- CREATE TABLE `user` (
--   `id` bigint(20) NOT NULL AUTO_INCREMENT,
--   `username` varchar(50) DEFAULT NULL,
--   `name` varchar(50) DEFAULT NULL,
--   `age` int(10) DEFAULT NULL,
--   `balance` decimal(10,2) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

